name: Build Android Kernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Build Environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libncurses5-dev bison flex libssl-dev libelf-dev gcc-aarch64-linux-gnu

    - name: Build Kernel
      run: |
        export ARCH=arm64
        export CROSS_COMPILE=aarch64-linux-gnu-
        make sm8250_defconfig sm8250.config
        make ARCH=arm64 -j$(nproc)

    - name: Install Modules
      run: |
        export ARCH=arm64
        export CROSS_COMPILE=aarch64-linux-gnu-
        make modules_install INSTALL_MOD_PATH=modules_install

    - name: Create Artifact Directory
      run: mkdir -p artifacts

    - name: Copy Artifacts
      run: |
        cp arch/arm64/boot/Image artifacts/
        #cp arch/arm64/boot/dts/*.dtb artifacts/  # Include device tree files
        cp -r modules_install/lib/modules artifacts/lib/  # Copy modules into proper structure
        cp vmlin* artifacts/

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: artifacts/*
